### ISSUE TITLE
Running Inference/Testing on Multiple GPUs

### ISSUE THREAD

**Issue by archiki** [anicolson/DeepXi#40]
Hi @anicolson!
I have trained a model on my custom noise dataset and have been trying to run inference and testing. When testing I observe that after loading the files for inference, I encounter OOM error. Although I was able to train with 1 GPU, with memory about ~10GB, testing requires more space. (Is this expected behavior?) I have access to multiple GPUs, so can you tell me if and how can I use multiple GPUs for the purpose of testing. This is not immediately straightforward from run.sh. Also, can you elaborate on how by just specifying the version does your code select the best iteration?
Thanks in advance!

**Comment by anicolson** [comment]
Hi,

How big are the files in your test set? If they are big, try reducing the mbatch_size in run.sh.

run.sh GPU=0,1

Will give you access to your first 2 GPUs.

Alternatively, you can run inference on CPU by using

run.sh GPU=999

In run.sh,  —test_epoch specifies the epoch to test/infer from.

Feel free to ask for more help,
Aaron.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by archiki** [comment]
They are librispeech test clean files. This is the error
`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[2620,2185,257] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:ConcatV2] name: concat
`
Can you confirm if I have understood the error correctly? I am actually using GPUs 2 and 3.
Thanks

**Comment by anicolson** [comment]
Use GPU=2,3 instead. Are you able to tell me which line of deepxi/model.py the problem occurs?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by archiki** [comment]
Hi,
I have used the GPU command correctly. The line 344, `xi_bar_hat_batch = self.model.predict(x_STMS_batch, batch_size=1, verbose=1)` is causing the error. I dont think the `device:GPU:0` in the error looks right. As of now, my GPU:0 is occupied with some other task. I have changed mbatch_size to 1, yet the error persists. The training however happened on GPU:0.

These are all the relevant prints:
`Processing observations...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2620/2620 [00:18<00:00, 140.89it/s]`
`Performing inference...
2620/2620 [==============================] - 87s 33ms/step`
`Traceback (most recent call last):
  File "main.py", line 115, in <module>
    stats_path=args.data_path,
  File "/home/archiki/DeepXi/deepxi/model.py", line 344, in test
    xi_bar_hat_batch = self.model.predict(x_STMS_batch, batch_size=1, verbose=1)
`

**Comment by anicolson** [comment]
Ok.

So I wanted to see if I could find the problem.

test-clean of librispeech can be loaded by including the following in run.sh

````
set -o noglob

TEST_X_PATH=/home/aaron/set/librispeech/LibriSpeech/test-clean/*/*

TEST_S_PATH=/home/aaron/set/librispeech/LibriSpeech/test-clean/*/*
````

And by running:
```
./run.sh VER="resnet-1.0c" TEST=1 
```
7GB is used:

![image](https://user-images.githubusercontent.com/26111230/83956234-0972b400-a89f-11ea-81c8-32230b5f26f7.png)


You must change from line 364 in deepxi/model.py from
```
noise_source = test_x_base_names[i].split("_")[-2]
snr_level = int(test_x_base_names[i].split("_")[-1][:-2])
```
to 

```
try: noise_src = test_x_base_names[i].split("_")[-2]
except IndexError: noise_src = "Null"
if noise_src == "Null": snr_level = 0
else: snr_level = int(test_x_base_names[i].split("_")[-1][:-2])
```
And then it works.

Running 

./run.sh VER="resnet-1.0c" TEST=1 GPU=2,3

will use GPUs 2 and 3. As can be seen from:

```
def gpu_config(gpu_selection, log_device_placement=False):
	"""
	Selects GPU.
	Argument/s:
		gpu_selection - GPU to use.
		log_device_placement - log the device that each node is placed on.
	"""
	os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
	os.environ["CUDA_VISIBLE_DEVICES"]=str(gpu_selection)
	gpus = tf.config.experimental.list_physical_devices('GPU')
	for gpu in gpus: tf.config.experimental.set_memory_growth(gpu, True)
```

we are only allowing the program to use GPUs 2 and 3, which the program sees as GPU0 and GPU1. I suggest monitoring your GPU usage using `nvidia-smi`.

Hope this helps,
Aaron.

**Comment by archiki** [comment]
Hi,
Thanks for the information. I think the multiple GPU setup does not work very well. In that case, you should consider inferring/testing in multiple batches instead of 1.  That should resolve this. I have one other thing to ask. I noticed that the result metrics were very poor for the model trained on my noise dataset. I found most of the y's to be filled with 0s only. The pesq is even returning nans. Surprisingly, my validation loss was also much smaller than my training loss (about 1/40 th). Do you have an explanation for this and some way of fixing this?
Also, can you point me to the implementation of the function that adds noise? I wanted to see if and how our methods of adding noise differ.
Thanks,

**Comment by anicolson** [comment]
The `add_noise` function:

https://github.com/anicolson/DeepXi/blob/858e96453dd1fe18d9672025bf388995c9da6896/deepxi/sig.py#L216

It may be easier for me to pinpoint the issue if you list any changes you have made, and describe the training, testing, and validation sets clearly.

Regards,
Aaron
